### ISSUE TITLE
Repeated is not recognized

### ISSUE THREAD

**Issue by halirutan** [halirutan/Wolfram-Language-IntelliJ-Plugin-Archive#31]
In the following code

```
Fun[1, 0.., {m___}, OptionsPattern[]] := 1;
```

the `Repeated` statement seems to confuse the plugin. The code is flagged as an error with the description "More input expected". I'm using  Idea 2016.1.1 with the Plugin Version: 1.3.4 on Fedora Linux 22.

**Comment by halirutan** [comment]
## One word as defense of the current implementation

In the [Operator Input Form](http://reference.wolfram.com/language/tutorial/OperatorInputForms.html) tutorial that should list all things with decreasing precedence, clearly on the top of the table one finds forms representing numbers. This means, that number forms tokenize together in precendence of other things and since this document was one crucial source of information for the implementation of the plugin, it is no wonder the bug appeared. When number forms would bind stronger than other operators, something like `0..` should be parsed as `(0.).`

But this is not the case. It is even worse, because `0....` could be parsed as `(0.)...` but brings an error instead. One quick workaround for the plugin is to write

````
Fun[1, (0).., {m___}, OptionsPattern[]] := 1;
````

## Information to discuss how to fix this

In the implementation of the plugin, the problem is based in the lexer and can be understood easily. In the lexing process, [numbers are identified](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/blob/b5528a128c5f958b1f9b33705d4dc0c566cdcc85/src/de/halirutan/mathematica/lexer/Mathematica.flex#L77-L77) before all of the many operators that exist. What happens is, that in

```
f[0..] := blub
```

the `0.` part is tokenized as a number which leave only the second `.` which is then identified as `Dot`. This creates a mess for the parser which correctly says that there is an error, because what the parser sees is `f[(0.).]`.

**Comment by vsht** [comment]
Thanks for the explanation and the workaround (the bug was originally filled  by me).

You should consider updating README.md, since the statement

> For issue- and bug-tracking Jetbrains YouTrack is used. If you find bugs, experience weird behavior or have feature suggestions please create a new issue there. Of course I will answer any issues that are reported through GitHub as well.

made me think that  I should report bugs on YouTrack.

Cheers,
Vladyslav

**Comment by halirutan** [comment]
@vsht Yes, I will update the readme. I already changed the website and forgot that I have mentioned the bugtracker in the readme. Btw, sometimes we discuss things [here in chat](http://chat.stackexchange.com/rooms/8636/intellijidea-plugin-for-mathematica).

**Comment by rsmenon** [comment]
A simpler workaround would be to write `f[0 ..]` or `f[0. ..]`. Not only is this unambiguous for the parser, it is unambiguous for the human as well and is definitely cleaner code.

I would strongly argue for keeping the current behavior as is and not add any additional complexity to the parser to try and match the behavior of the front end (which, btw, is not documented anywhere). I think that the auto-whitespace, auto-indent behavior of the _Mathematica_ front end (and implicit `Times` on whitespace in the kernel) is contributing to poor coding styles & discipline in the community (e.g. persistence on fancy "one liners", chaining too many operations together, lack of whitespace between operators, etc.). This instance is one example where I think the plugin should deviate from the default behavior in the front end because it is promoting a healthy practice.

**Comment by vsht** [comment]
Well, I usually develop in Wolfram Workbench, where `f[0..]` is not consider an error. So it is not the front end behavior that I'm looking for. 

I think one should also explicitly distinguish between obvious syntax errors and "bad" coding style. So if the plugin considers `f[0..]` to be bad style, it should write it like that but not flag it as an error, since the code by itself works.

Anyhow, I just  wanted to test how it is to develop with IntelliJ instead of Wolfram Workbench, and reported the first issue I spotted. It is of course up to you guys, how you want to treat that.

**Comment by rsmenon** [comment]
That is a fair point actually. I think it is reasonable to expect an ambiguous-but-correct-syntax to not show up as a syntax error. Or at the very least, it should display a more helpful text suggesting an alternate style when hovering on the error. 

I think showing a "helpful message on error" might be easier since it can be handled in the annotations, whereas "not showing an error" would certainly involve modifying the parser. @halirutan is the best judge of which is the technically easier option of the two though.

**Comment by halirutan** [comment]
@vsht @rsmenon Unfortunately, it doesn't matter if I chose to make the plugin accept the code or make it highlight it as warning. In any way, the parser and especially the lexer needs to be adapted. Currently, the recognition of numbers is a big, nested regular expression to include all possible cases how numbers can be written.
To recognize the cases where the number has a dot at the end like `42.` or `16^^A1.` or ```41``4.``` I need to tear this big regular expression apart and separate those cases. Then, I either need to make the conditional handling of dots following such a number directly in the lexer or I do it at parsing time where I have to change lexer tokens. Currently, for `0..` I get two tokens `NUMBER` and `DOT`, where the first one is the `0.` part and the latter one is only the `.`
I would need to remap these tokens to `NUMBER`, now consisting only of the `0` and `REAPEATED`.

This sounds almost trivial, but I'm making changes in the very core of the parsing which almost cries for trouble. Additionally, it would definitely make the lexing and parsing more complex which leads to a slow down. The magnitude of this slowdown might be tiny or it doesn't; it is hard to say.

I will leave this issue open, but won't start working right away on this as it is a very small benefit for the amount of work that is behind it.

> Anyhow, I just wanted to test how it is to develop with IntelliJ instead of Wolfram Workbench, and reported the first issue I spotted.

And I really do appreciate it and I would love if you continue to report things.

**Comment by halirutan** [comment]
Unfixable without reworking how numbers are tokenized and parsed.
