### ISSUE TITLE
Pattern not highlighted properly

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Wolfram-Language-IntelliJ-Plugin-Archive#59]
The following pattern isn't highlighted properly:

![image](https://cloud.githubusercontent.com/assets/1212871/20665661/c45e9b7a-b560-11e6-88e0-520691b4b6b0.png)

    Replace[result, HoldComplete[ReturnPacket[{_ :> expr_}]] :> HoldComplete[expr]]

Compare the Front End:

![image](https://cloud.githubusercontent.com/assets/1212871/20665686/d62c50d6-b560-11e6-92c0-7121a26fa939.png)

**Comment by halirutan** [comment]
Yes, it's a problem in the resolver of `expr` on the right side. It seems I don't dive into `HoldComplete` or the resolver gets confused with the `_ :> expr_` part. I can find the reason for the behavior fast, but I think we need to discuss the general approach of how symbols are resolved. I'll look into to this.

**Comment by halirutan** [comment]
Upfront, it is not going to be a quick fix, but we decide to go for it, I'm all in because it means that we can improve the highlighting of locally bound variables (patterns in rules and function definitions, and highlighting of `Module` and friends). As it stands, what you are using for so long now is still my first implementation of how to find locally bound symbols.

OK, let's start a bit of explanation: The first `RuleDelayed` is the reason why it is not recognized. I'm using a very compact way of how a definition point (in `exp_ :> exp` the `exp_` is the definition point) of a variable is found. I visit every symbol (let's call it `startSym`) in the file and for each symbol, I walk the tree upwards and check if I found `Module`, ... , or `:>`. If I find one of these, I dive again down the tree. For `Module` this means, I dive down the first argument of it ([source line](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/blob/23ca9be854c9dec459ed39daf1538877824da2af/src/de/halirutan/mathematica/parsing/psi/util/LocalDefinitionResolveProcessor.java#L115-L115)) extracting all symbols from there. Then I compare them to the `startSym`. If the names match, this is the definition point of `startSym`.

For `RuleDelayed` the algorithm itself is a bit more involved but basically the same. If I meet a `RuleDelayed` I dive back down to its first argument and search for a valid pattern that has the same name as `startSym`. Since I always only dive down the first child, this rule applies even when I see the `_ :> exp_` and therefore I cannot find the definition of `exp` on the rhs.

So what I need to do is to separate these two things. But before I touch this, I would like to have a *Mathematica* implementation for the following:

Assuming I have a symbol `startSym` and the `lhs` of a `RuleDelayed` we need a function `findDeclaration[lhs, startSym]` that returns the symbol in `lhs` where `startSym` is declared.

If we have this algorithm as correct as possible, we can use it instantly to find the place of declaration in the lhs of function definitions.
